---
- name: Create new group
  group:
    name: "{{ group_name }}"
    state: present

- name: Create new user with home directory
  user:
    name: "{{ item.name }}"
    password: "{{ item.password_hash }}"
    shell: /bin/bash
    groups: "{{ group_name }},sudo"
    append: yes
    create_home: yes
    home: "/home/{{ item.name }}"
  loop: "{{ users }}"
  
- name: Ensure .ssh directory exists for user
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
  loop: "{{ users }}"

- name: Place the SSH key for user
  copy:
    src: "{{ public_key_path }}"
    dest: "/home/{{ item.name }}/.ssh/authorized_keys"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
  loop: "{{ users }}"
